Added upload button
GEWIS/gewisweb pull request #1800
Opened 2024-03-25 17:41 UTC by BHenkemans

Closes GH-1715

2024-03-25 17:52 UTC, tomudding requested changes
One minor change requested, otherwise this looks great!

2024-03-25 17:52 UTC, tomudding commented on module/Decision/view/decision/decision/view.phtml
> +            <?php if ($this->acl('decision_service_acl')->isAllowed('meeting','upload_document') && $meeting->getType()->value != "BV"): ?>
Please use the `MeetingTypes` enum:

```php
MeetingTypes::BV
```

And also strict `===` comparisons

2024-04-18 14:42 UTC, tomudding commented
@BHenkemans when you have time, can you rebase this?

2024-08-02 21:04 UTC, BHenkemans commented
Abandoned. Will restart.

2024-08-02 21:04 UTC, closed without merging