Added FlashMessenger to authorization actions.
GEWIS/gewisweb pull request #1884
Opened 2024-08-02 22:46 UTC by BHenkemans

# Description
Added FlashMessenger to authorization actions.

## Related issues/external references

Resolves GH-1825

## Types of changes

- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [X] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
- [ ] Documentation improvement _(no changes to code)_
- [ ] Other _(please specify)_

2024-08-04 13:16 UTC, BHenkemans commented
A merge was the only way of solving the po-file problems. Rebasing never got me the right result :(

2024-08-06 09:45 UTC, tomudding requested changes
> A merge was the only way of solving the po-file problems. Rebasing never got me the right result :(

It can happen; I usually select `theirs` and redo the translations on `ours` (assuming the PO editor you are using is capable enough to keep some history).

2024-08-06 09:45 UTC, tomudding commented on module/Decision/src/Controller/DecisionController.php
> +                ->translate('You are not allowed to authorize someone'));
Please remove this such that we can assert that the `throw` is the only thing that will happen here.

2024-08-06 09:45 UTC, tomudding commented on module/Decision/src/Controller/DecisionController.php
> +                ->translate('You are not allowed to revoke authorizations.'));
Same here

2024-08-06 10:21 UTC, tomudding approved these changes

2024-08-06 10:22 UTC, tomudding commented
<3

2024-08-06 10:22 UTC, merged